- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx:1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Ensure Nginx is running and enabled at boot
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove html folder
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html folder
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download zip file from URL
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip"
      dest: "/tmp/frontend.zip"

  - name: Unarchive a file that is already on the remote  frontend machine
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove default nginx conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy files
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx services
    ansible.builtin.service:
      service: nginx
      state: restarted