- name: configuring mongodb server
  become: yes
  hosts: mongodb
  tasks:
  - name: copy mongodb repo
    ansible.builtin.cpy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongodb.conf
      regexp: '127.0.0.1'
      replace: 0.0.0.0

  - name: restart mongodb
    ansible.builtin.service:
      name: mongodb
      state: restarted