- name: configure user component
  hosts: user
  become: yes
  tasks:
  - name: disable nodejs default module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs recommended module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create dierectory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  # this module thinks file exist on ansible server, needs to extract o nto remote machine
  # remote_src: yes means files already exist in user server
  - name: extract code to the app
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
    path: /app

  - name: copy services
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemctl daemon reload
    ansible.builtin.service:
      daemon_reload: true

  - name: enable and start user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes